replacing the required tensorflow dependency with tensorflow-macos to support Apple Silicon
The privacy package can't be installed on Apple Silicon because Tensorflow provides a separate package for macOS.

```shell
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4 (from tensorflow-privacy) (from versions: 2.13.0rce, 2.13.0rc1)
ERROR: No matching distribution found for tensorflow~=2.
```